<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wrong credentialsInvalid username or password</name>
   <tag></tag>
   <elementGuidId>412b2d87-fd38-4fe7-bf47-0e5f57d40b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error_box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error_box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6376ac9a-65cc-4cbd-8bd3-a1876a1003bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pam _3-95 _9ay3 uiBoxRed</value>
      <webElementGuid>78bf0ea1-d6d1-4ace-8a9c-0d410bc466a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d9b1ce8f-d25a-4b04-97c4-28fa7f0e299a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5a9957f-ac80-42e6-bb65-3b86a225e8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error_box</value>
      <webElementGuid>f7cfd74f-a556-4ca6-8c5e-bcbc57664e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wrong credentialsInvalid username or password</value>
      <webElementGuid>6fe2688d-8946-4a7c-bdd0-1297e4176dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error_box&quot;)</value>
      <webElementGuid>3af1e915-e47d-4f79-8279-46d449cec001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error_box']</value>
      <webElementGuid>ad42410f-b218-4b12-b438-e90fe92c2796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div</value>
      <webElementGuid>7f54201e-3eb2-4a5f-b86c-9e29c2707419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to Facebook'])[2]/following::div[2]</value>
      <webElementGuid>6aca9c13-2cfd-44c7-a804-373fb685dcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>fd748f6b-b175-44a6-98ca-84cee3728b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error_box' and (text() = 'Wrong credentialsInvalid username or password' or . = 'Wrong credentialsInvalid username or password')]</value>
      <webElementGuid>809fde89-1bb5-4366-bca1-4e2b1f094492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
